FROM fedora
RUN dnf -y install git 
RUN dnf -y install gcc 
RUN dnf -y install diffutils 
RUN dnf -y install ncurses-*
RUN git clone https://github.com/alt-romes/programmer-calculator.git
WORKDIR /programmer-calculator
Run make install