- name: Pierwsze zadanie
  hosts: Machines
  become: true
  tasks:
    - name: Pierwszy krok, stworzenie katalogu
      file:
        path: ~/uploads
        state: directory
        mode: 0755
    - name: Drugi krok, skopiowanie pliku env
      copy:
        src: env
        dest: ~/uploads/env
        mode: 0755
    - name: Trzeci krok, sprawdzanie dnf-plugins
      dnf:
        name: dnf-plugins-core
        state: present
      become: yes
    - name: Czwarty krok, pobieranie repozytorium Dockera
      command: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
      become: yes
    - name: Szósty krok, instalacja Dockera
      dnf:
        name: "{{ item }}"
        state: present
      with_items:
        - docker-ce
      become: yes
    - name: Siódmy krok, start Dockera
      systemd:
        name: docker
        state: started
        enabled: yes
      become: yes
    - name: nginx
      docker_container:
        name: nginx
        image: nginx
        state: started
        ports:
          - "80:80"